dist: xenial
language: go
os: linux
sudo: required

go:
- 1.x

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_install:
- scripts/ci/check-pr

install:
- scripts/ci/install-deps

before_script:
- sudo minikube start --vm-driver=none --kubernetes-version="v1.11.0" --extra-config=apiserver.v=4
- sudo chown -R $USER ${HOME}/.{mini,}kube
- kubectl config use-context minikube
- scripts/ci/install-olm-local

jobs:
  include:
  - name: Scorecard on minikube
    script: scripts/ci/test-pr
